version: '3'

services:
  redis:
    image: redis
    ports:
      - "6377:6379"

  api:
    build: .
    command: /opt/app/start.sh
    ports:
      - "8086:80"
    depends_on:
      - redis
    env_file:
      - .env