version: '3'

services:
  redis:
    image: redis
    ports:
      - "6377:6379"

  api:
    build: .
    command: tail -f /dev/null
    ports:
      - "8086:8086"
    depends_on:
      - redis
    env_file:
      - .env